CREATE DATABASE IF NOT EXISTS JWeb

USE JWeb;

DROP TABLE IF EXISTS JWeb.Clients;
CREATE TABLE JWeb.Clients (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(32) NOT NULL,
  firstName VARCHAR(32) NOT NULL,
  email VARCHAR(32) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE (email)
) ENGINE = INNODB;


DROP TABLE IF EXISTS JWeb.Admin;
CREATE TABLE JWeb.Admin (
	id INT(11) NOT NULL AUTO_INCREMENT,
	login VARCHAR(32) NOT NULL,
	password VARCHAR(32) NOT NULL,
	PRIMARY KEY (id)
) ENGINE = INNODB;


DROP TABLE IF EXISTS JWeb.Comments;
CREATE TABLE JWeb.Comments (
	id INT(11) NOT NULL AUTO_INCREMENT,
	name VARCHAR(32) NOT NULL,
	comment VARCHAR(512) NOT NULL,
	PRIMARY KEY (id)
) ENGINE = INNODB;

DROP TABLE IF EXISTS JWeb.News;
CREATE_TABLE JWeb.News (
	id INT(11) NOT NULL AUTO_INCREMENT,
	title VARCHAR(32) NOT NULL,
	body VARCHAR(512) NOT NULL,
	date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
) ENGINE = INNODB;